site_name: StoryDredge Documentation
site_description: Documentation for the StoryDredge newspaper processing pipeline
site_author: StoryDredge Team

repo_url: https://github.com/yourusername/storydredge
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - search.suggest
    - search.highlight

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - User Guide: user_guide.md
  - Project:
      - Roadmap: ROADMAP.md
      - Architecture: architecture.md
  - Components:
      - Overview: components/index.md
      - Fetcher: components/fetcher.md
      - Cleaner: components/cleaner.md
      - Splitter: components/splitter.md
      - Classifier: components/classifier.md
      - Formatter: components/formatter.md
      - Performance: components/performance.md
  - Development:
      - Setup: development/setup.md
      - Contributing: development/contributing.md
      - Testing: development/testing.md
  - API Reference:
      - Overview: api/overview.md
      - Fetcher API: api/fetcher.md
      - Cleaner API: api/cleaner.md
      - Splitter API: api/splitter.md
      - Classifier API: api/classifier.md
      - Formatter API: api/formatter.md
      - Pipeline API: api/pipeline.md
      - Benchmarking API: api/benchmarking.md
      - Utilities API: api/utils.md 